- name: Install Node.js
  yum:
    name: nodejs
    state: present

- name: Install npm
  yum:
    name: npm
    state: present

- name: Copy application code
  copy:
    src: /Users/ajinkyapatil/mywork/Multi-Tier_Web_Application/app
    dest: /home/ec2-user/app/
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Install application dependencies
  command: npm install
  args:
    chdir: /home/ec2-user/app/app/

- name: Create Node.js service
  copy:
    content: |
      [Unit]
      Description=Node.js Application

      [Service]
      ExecStart=/usr/bin/node /home/ec2-user/app/app/index.js
      WorkingDirectory=/home/ec2-user/app/app
      Restart=always
      User=ec2-user
      Group=ec2-user

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node-app.service
  notify:
    - Reload systemd

- name: Start Node.js application
  systemd:
    name: node-app
    state: started
    enabled: yes
    daemon_reload: yes

