- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy static HTML page
  copy:
    src: /Users/ajinkyapatil/mywork/Multi-Tier_Web_Application/ansible/roles/webserver/files/index.html
    dest: /usr/share/nginx/html/index.html

