- name: Install PostgreSQL
  yum:
    name: postgresql15-server
    state: present

- name: Initialize PostgreSQL database
  command: /usr/bin/postgresql-setup initdb

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

